name: Development

on:
  push:
    branches: ci-testing

jobs:
  # cypress:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.10.0

  #     - name: 'install npm@latest'
  #       run: npm i -g npm@latest

  #     - name: Install Dependencies
  #       run: npm install

  test:
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
      CYPRESS_API_URL: ${{ secrets.CYPRESS_API_URL }}
      CYPRESS_REGULAR_EMAIL: ${{ secrets.CYPRESS_REGULAR_EMAIL }}
      CYPRESS_REGULAR_PASSWORD: ${{ secrets.CYPRESS_REGULAR_PASSWORD }}
      CYPRESS_ADMIN_EMAIL: ${{ secrets.CYPRESS_ADMIN_EMAIL }}
      CYPRESS_ADMIN_PASSWORD: ${{ secrets.CYPRESS_ADMIN_PASSWORD }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      VITE_API_ENDPOINT: ${{ secrets.VITE_API_ENDPOINT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21.6.0

      - name: 'install npm@latest'
        run: npm i -g npm@latest

      - name: Install Dependencies
        run: npm install

      - name: Create cypress env file
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: cypress.env.json
          json: '{ "CYPRESS_BASE_URL": "${{ secrets.CYPRESS_BASE_URL }}", "CYPRESS_API_URL": "${{ secrets.CYPRESS_API_URL }}", "CYPRESS_REGULAR_EMAIL": "${{ secrets.CYPRESS_REGULAR_EMAIL }}", "CYPRESS_REGULAR_PASSWORD": "${{ secrets.CYPRESS_REGULAR_PASSWORD }}", "CYPRESS_ADMIN_EMAIL": "${{ secrets.CYPRESS_ADMIN_EMAIL }}", "CYPRESS_ADMIN_PASSWORD": "${{ secrets.CYPRESS_ADMIN_PASSWORD }}" }'

      - name: Check cypress env
        run: cat cypress.env.json

      - name: Test (E2E)
        run: npm run cypress:e2e:ci

      - name: Test (Components)
        run: npm run cypress:component
