name: Development

on:
  push:
    branches: dev

jobs:
  cypress:
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
      CYPRESS_API_URL: ${{ secrets.CYPRESS_API_URL }}
      CYPRESS_REGULAR_EMAIL: ${{ secrets.CYPRESS_REGULAR_EMAIL }}
      CYPRESS_REGULAR_PASSWORD: ${{ secrets.CYPRESS_REGULAR_PASSWORD }}
      CYPRESS_ADMIN_EMAIL: ${{ secrets.CYPRESS_ADMIN_EMAIL }}
      CYPRESS_ADMIN_PASSWORD: ${{ secrets.CYPRESS_ADMIN_PASSWORD }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      VITE_API_ENDPOINT: ${{ secrets.VITE_API_ENDPOINT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21.6.0

      - name: 'install npm@latest'
        run: npm i -g npm@latest
        

      - name: Install Dependencies
        run: npm install

      - name: Start Server
        run: npm run start:test & # Start your server in the background

      - name: Debug Logging
        run: echo -E "My secret value is ${{ secrets.MY_SECRET }}"
        
      - name: Test (E2E)
        run: npm run cypress:e2e:ci -- --headed

      - name: Test (Components)
        run: npm run cypress:component
