name: Development

on:
  push:
    branches: ci-testing

jobs:
  # cypress:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.10.0

  #     - name: 'install npm@latest'
  #       run: npm i -g npm@latest

  #     - name: Install Dependencies
  #       run: npm install

  test:
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
      CYPRESS_API_URL: ${{ secrets.CYPRESS_API_URL }}
      CYPRESS_REGULAR_EMAIL: ${{ secrets.CYPRESS_REGULAR_EMAIL }}
      CYPRESS_REGULAR_PASSWORD: ${{ secrets.CYPRESS_REGULAR_PASSWORD }}
      CYPRESS_ADMIN_EMAIL: ${{ secrets.CYPRESS_ADMIN_EMAIL }}
      CYPRESS_ADMIN_PASSWORD: ${{ secrets.CYPRESS_ADMIN_PASSWORD }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      VITE_API_ENDPOINT: ${{ secrets.VITE_API_ENDPOINT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21.6.0

      - name: 'install npm@latest'
        run: npm i -g npm@latest

      - name: Install Dependencies
        run: npm

      - name: Check if secrets are empty
        run: |
          if [ -z "${{ secrets.CYPRESS_BASE_URL }}" ]; then
            echo "BASE URL does not exist"
          else
            echo "BASE URL exists"
          fi

          if [ -z "${{ secrets.CYPRESS_API_URL }}" ]; then
            echo "API URL does not exist"
          else
            echo "API URL exists"
          fi

      - name: Test (E2E)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          install: false
          wait-on: ${{ secrets.CYPRESS_BASE_URL }}, ${{ secrets.CYPRESS_API_URL }}
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_API_URL: ${{ secrets.CYPRESS_API_URL }}
          CYPRESS_REGULAR_EMAIL: ${{ secrets.CYPRESS_REGULAR_EMAIL }}
          CYPRESS_REGULAR_PASSWORD: ${{ secrets.CYPRESS_REGULAR_PASSWORD }}
          CYPRESS_ADMIN_EMAIL: ${{ secrets.CYPRESS_ADMIN_EMAIL }}
          CYPRESS_ADMIN_PASSWORD: ${{ secrets.CYPRESS_ADMIN_PASSWORD }}

      - name: Test (Components)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          install: false
          component: true
          wait-on: ${{ secrets.CYPRESS_BASE_URL }}, ${{ secrets.CYPRESS_API_URL }}
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_API_URL: ${{ secrets.CYPRESS_API_URL }}
          CYPRESS_REGULAR_EMAIL: ${{ secrets.CYPRESS_REGULAR_EMAIL }}
          CYPRESS_REGULAR_PASSWORD: ${{ secrets.CYPRESS_REGULAR_PASSWORD }}
          CYPRESS_ADMIN_EMAIL: ${{ secrets.CYPRESS_ADMIN_EMAIL }}
          CYPRESS_ADMIN_PASSWORD: ${{ secrets.CYPRESS_ADMIN_PASSWORD }}
